"use client";
import { Toaster } from "@/components/ui/sonner";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Hệ Thống Quay Số May Mắn",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const DATA_GIAI_DB = use(getDataGiaiDb());
  // const DATA_GIAI_1 = use(getDataGiai1());
  // const DATA_GIAI_2 = use(getDataGiai2());
  // const DATA_GIAI_3 = use(getDataGiai3());

  // console.log("DATA_GIAI_DB === ", DATA_GIAI_DB);
  // const { setDataGiai1, setDataGiai2, setDataGiai3, setDataGiaiDb } =
  //   useUserDataStore();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
