import { getDataThamGia } from "@/actions/act_data";
import StoreProvider from "@/components/store-provider";
import { Toaster } from "@/components/ui/sonner";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Hệ Thống Quay Số May Mắn",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const DATA_THAM_GIA = await getDataThamGia();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider dataThamGia={DATA_THAM_GIA}>
          {children}
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
